services:
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - PROJECT_ROOT=/app
    volumes:
      - ./oci:/app/oci
      - ./data:/app/data
      - ./ssh:/app/ssh
      - /var/run/docker.sock:/var/run/docker.sock

  hunter:
    image: ghcr.io/oracle/oci-cli:latest
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - ./oci:/oracle/.oci
      - ./data:/data
      - ./ssh:/ssh
    entrypoint:
      - /bin/bash
      - -c
      - "until [ -f /data/hunter.sh ]; do echo 'Waiting for /data/hunter.sh...'; sleep 2; done; exec /bin/bash /data/hunter.sh"
